!classDefinition: #Pepe category: #Ejercicio1!
DenotativeObject subclass: #Pepe
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepe class' category: #Ejercicio1!
Pepe class
	instanceVariableNames: ''!

!Pepe class methodsFor: '-- all --' stamp: 'MS 3/18/2024 21:01:03'!
hola
	^ 'chau'! !
